[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:root@localhost/dinamite'
UPLOAD_PATH = "os.path.dirname(os.path.abspath(__file__)) + '/uploads'"
SECRET_KEY = "vasco"
EXTENSIONS = [
    "dinamite.ext.appearance:init_app",
    "dinamite.ext.database:init_app",
    "dinamite.ext.protect:init_app",
    "dinamite.blueprints.webui:init_app",
    "dinamite.blueprints.restapi:init_app",
]


[production]
SQLALCHEMY_DATABASE_URI = 'postgres:///...'